### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by PertuyF** [kbhoehn/IgPhyML#1]
Hi!

I am interested into packaging your software for `conda`. Could you evaluate creating a Git tag and a release tarball for the current version of this repo?
Would be great for reproducibility.

**Comment by kbhoehn** [comment]
Hi! I'd be happy to, however, development for IgPhyML has largely moved to bitbucket, and the package itself has changed quite a bit: https://bitbucket.org/kbhoehn/igphyml
Here's the documentation for the current release on that site: https://changeo.readthedocs.io/en/version-0.4.5/examples/igphyml.html
And a paper describing the updates: https://www.biorxiv.org/content/10.1101/558825v2

Are you able to do the packaging you're interested in with that repo? If so that would be preferable. If not I can add a tag and release tarball for this repo.

**Comment by PertuyF** [comment]
I came here from your paper, but your other repo already has Git Tags so it should be OK for packaging!
Thanks for pointing me there, I'll close this issue an reopen on Bitbucket if required.
